services:
  copypaste:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      COPYPASTE_AUTH_TOKEN: "${COPYPASTE_AUTH_TOKEN:-}"
      ROCKET_LOG_LEVEL: "${ROCKET_LOG_LEVEL:-normal}"
    restart: unless-stopped
