version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - DATABASE_URL=sqlite:/app/data/pastes.db
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
