services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./static:/static
    restart: unless-stopped
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=8000
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
