/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as HealthRouteImport } from './routes/health'
import { Route as InstallRouteImport } from './routes/install'
import { Route as RecentsRouteImport } from './routes/recents'
import { Route as ApiV1RouteImport } from './routes/api/v1'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as RawIdRouteImport } from './routes/raw.$id'
import { Route as ApiV1PastesRouteImport } from './routes/api/v1.pastes'
import { Route as ApiV1PastesIdRouteImport } from './routes/api/v1.pastes.$id'
import { Route as ApiV1PastesIdRawRouteImport } from './routes/api/v1.pastes.$id.raw'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentsRoute = RecentsRouteImport.update({
  id: '/recents',
  path: '/recents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1Route = ApiV1RouteImport.update({
  id: '/api/v1',
  path: '/api/v1',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RawIdRoute = RawIdRouteImport.update({
  id: '/raw/$id',
  path: '/raw/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PastesRoute = ApiV1PastesRouteImport.update({
  id: '/pastes',
  path: '/pastes',
  getParentRoute: () => ApiV1Route,
} as any)
const ApiV1PastesIdRoute = ApiV1PastesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1PastesRoute,
} as any)
const ApiV1PastesIdRawRoute = ApiV1PastesIdRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => ApiV1PastesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/health': typeof HealthRoute
  '/install': typeof InstallRoute
  '/recents': typeof RecentsRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/p/$id': typeof PIdRoute
  '/raw/$id': typeof RawIdRoute
  '/api/v1/pastes': typeof ApiV1PastesRouteWithChildren
  '/api/v1/pastes/$id': typeof ApiV1PastesIdRouteWithChildren
  '/api/v1/pastes/$id/raw': typeof ApiV1PastesIdRawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/health': typeof HealthRoute
  '/install': typeof InstallRoute
  '/recents': typeof RecentsRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/p/$id': typeof PIdRoute
  '/raw/$id': typeof RawIdRoute
  '/api/v1/pastes': typeof ApiV1PastesRouteWithChildren
  '/api/v1/pastes/$id': typeof ApiV1PastesIdRouteWithChildren
  '/api/v1/pastes/$id/raw': typeof ApiV1PastesIdRawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/health': typeof HealthRoute
  '/install': typeof InstallRoute
  '/recents': typeof RecentsRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/p/$id': typeof PIdRoute
  '/raw/$id': typeof RawIdRoute
  '/api/v1/pastes': typeof ApiV1PastesRouteWithChildren
  '/api/v1/pastes/$id': typeof ApiV1PastesIdRouteWithChildren
  '/api/v1/pastes/$id/raw': typeof ApiV1PastesIdRawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/health'
    | '/install'
    | '/recents'
    | '/api/v1'
    | '/p/$id'
    | '/raw/$id'
    | '/api/v1/pastes'
    | '/api/v1/pastes/$id'
    | '/api/v1/pastes/$id/raw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/health'
    | '/install'
    | '/recents'
    | '/api/v1'
    | '/p/$id'
    | '/raw/$id'
    | '/api/v1/pastes'
    | '/api/v1/pastes/$id'
    | '/api/v1/pastes/$id/raw'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/health'
    | '/install'
    | '/recents'
    | '/api/v1'
    | '/p/$id'
    | '/raw/$id'
    | '/api/v1/pastes'
    | '/api/v1/pastes/$id'
    | '/api/v1/pastes/$id/raw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HealthRoute: typeof HealthRoute
  InstallRoute: typeof InstallRoute
  RecentsRoute: typeof RecentsRoute
  ApiV1Route: typeof ApiV1RouteWithChildren
  PIdRoute: typeof PIdRoute
  RawIdRoute: typeof RawIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recents': {
      id: '/recents'
      path: '/recents'
      fullPath: '/recents'
      preLoaderRoute: typeof RecentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1': {
      id: '/api/v1'
      path: '/api/v1'
      fullPath: '/api/v1'
      preLoaderRoute: typeof ApiV1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw/$id': {
      id: '/raw/$id'
      path: '/raw/$id'
      fullPath: '/raw/$id'
      preLoaderRoute: typeof RawIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/pastes': {
      id: '/api/v1/pastes'
      path: '/pastes'
      fullPath: '/api/v1/pastes'
      preLoaderRoute: typeof ApiV1PastesRouteImport
      parentRoute: typeof ApiV1Route
    }
    '/api/v1/pastes/$id': {
      id: '/api/v1/pastes/$id'
      path: '/$id'
      fullPath: '/api/v1/pastes/$id'
      preLoaderRoute: typeof ApiV1PastesIdRouteImport
      parentRoute: typeof ApiV1PastesRoute
    }
    '/api/v1/pastes/$id/raw': {
      id: '/api/v1/pastes/$id/raw'
      path: '/raw'
      fullPath: '/api/v1/pastes/$id/raw'
      preLoaderRoute: typeof ApiV1PastesIdRawRouteImport
      parentRoute: typeof ApiV1PastesIdRoute
    }
  }
}

interface ApiV1PastesIdRouteChildren {
  ApiV1PastesIdRawRoute: typeof ApiV1PastesIdRawRoute
}

const ApiV1PastesIdRouteChildren: ApiV1PastesIdRouteChildren = {
  ApiV1PastesIdRawRoute: ApiV1PastesIdRawRoute,
}

const ApiV1PastesIdRouteWithChildren = ApiV1PastesIdRoute._addFileChildren(
  ApiV1PastesIdRouteChildren,
)

interface ApiV1PastesRouteChildren {
  ApiV1PastesIdRoute: typeof ApiV1PastesIdRouteWithChildren
}

const ApiV1PastesRouteChildren: ApiV1PastesRouteChildren = {
  ApiV1PastesIdRoute: ApiV1PastesIdRouteWithChildren,
}

const ApiV1PastesRouteWithChildren = ApiV1PastesRoute._addFileChildren(
  ApiV1PastesRouteChildren,
)

interface ApiV1RouteChildren {
  ApiV1PastesRoute: typeof ApiV1PastesRouteWithChildren
}

const ApiV1RouteChildren: ApiV1RouteChildren = {
  ApiV1PastesRoute: ApiV1PastesRouteWithChildren,
}

const ApiV1RouteWithChildren = ApiV1Route._addFileChildren(ApiV1RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HealthRoute: HealthRoute,
  InstallRoute: InstallRoute,
  RecentsRoute: RecentsRoute,
  ApiV1Route: ApiV1RouteWithChildren,
  PIdRoute: PIdRoute,
  RawIdRoute: RawIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
