#!/usr/bin/env bash
# auto-research.sh — Automated competitive intelligence for copypaste.fyi
# Fetches GitHub stats for competitors and trending Rust CLI tools,
# then creates a GitHub issue with the findings.

set -euo pipefail

DATE=$(date -u +"%Y-%m-%d")
REPORT_FILE=$(mktemp)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

gh_api() {
  # Wrapper around gh api that handles rate limits gracefully.
  # Returns empty JSON object on failure so downstream jq never breaks.
  local endpoint="$1"
  local result
  if result=$(gh api "$endpoint" 2>/dev/null); then
    echo "$result"
  else
    echo "{}"
  fi
}

gh_api_raw() {
  # Like gh_api but returns the raw JSON (for search results with .items).
  local endpoint="$1"
  local result
  if result=$(gh api "$endpoint" 2>/dev/null); then
    echo "$result"
  else
    echo '{"items":[]}'
  fi
}

safe_jq() {
  # jq that returns a fallback on failure
  local filter="$1"
  local fallback="${2:-n/a}"
  jq -r "$filter" 2>/dev/null || echo "$fallback"
}

# ---------------------------------------------------------------------------
# Competitor list
# ---------------------------------------------------------------------------

COMPETITORS=(
  "dutchcoders/transfer.sh"
  "PrivateBin/PrivateBin"
  "magic-wormhole/magic-wormhole"
  "schollz/croc"
  "timvisee/ffsend"
  "ekzhang/rustpad"
)

RUST_STARS=(
  "mitsuhiko/rye"
  "astral-sh/uv"
  "BurntSushi/ripgrep"
  "sharkdp/bat"
  "sharkdp/fd"
)

# ---------------------------------------------------------------------------
# Build report header
# ---------------------------------------------------------------------------

cat > "$REPORT_FILE" <<EOF
# Competitive Intelligence Report — $DATE

> Auto-generated by the \`auto-research\` workflow. [Trigger manually](../actions/workflows/auto-research.yml).

---

## 1. Direct Competitors (paste / file-sharing tools)

| Repository | Stars | Forks | Open Issues | Last Push | Description |
|------------|------:|------:|------------:|-----------|-------------|
EOF

# ---------------------------------------------------------------------------
# Fetch competitor stats
# ---------------------------------------------------------------------------

for repo in "${COMPETITORS[@]}"; do
  echo "Fetching $repo ..." >&2
  data=$(gh_api "repos/$repo")

  stars=$(echo "$data"    | safe_jq '.stargazers_count'  '?')
  forks=$(echo "$data"    | safe_jq '.forks_count'       '?')
  issues=$(echo "$data"   | safe_jq '.open_issues_count' '?')
  pushed=$(echo "$data"   | safe_jq '.pushed_at'         '?')
  desc=$(echo "$data"     | safe_jq '.description'       '')
  pushed_short="${pushed:0:10}"

  # Truncate long descriptions
  if [ "${#desc}" -gt 80 ]; then
    desc="${desc:0:77}..."
  fi

  echo "| [\`$repo\`](https://github.com/$repo) | $stars | $forks | $issues | $pushed_short | $desc |" >> "$REPORT_FILE"

  # Be nice to the API
  sleep 1
done

# ---------------------------------------------------------------------------
# Rust CLI star magnets
# ---------------------------------------------------------------------------

cat >> "$REPORT_FILE" <<'EOF'

---

## 2. Rust CLI Gold Standards (star magnets to learn from)

| Repository | Stars | Forks | Open Issues | Last Push | Topics |
|------------|------:|------:|------------:|-----------|--------|
EOF

for repo in "${RUST_STARS[@]}"; do
  echo "Fetching $repo ..." >&2
  data=$(gh_api "repos/$repo")

  stars=$(echo "$data"    | safe_jq '.stargazers_count'  '?')
  forks=$(echo "$data"    | safe_jq '.forks_count'       '?')
  issues=$(echo "$data"   | safe_jq '.open_issues_count' '?')
  pushed=$(echo "$data"   | safe_jq '.pushed_at'         '?')
  topics=$(echo "$data"   | jq -r '(.topics // []) | join(", ")' 2>/dev/null || echo "")
  pushed_short="${pushed:0:10}"

  echo "| [\`$repo\`](https://github.com/$repo) | $stars | $forks | $issues | $pushed_short | $topics |" >> "$REPORT_FILE"

  sleep 1
done

# ---------------------------------------------------------------------------
# Trending Rust repos (stars > 500, pushed recently)
# ---------------------------------------------------------------------------

# Use a date 90 days ago for the search window
SINCE_DATE=$(date -u -d "90 days ago" +"%Y-%m-%d" 2>/dev/null || date -u -v-90d +"%Y-%m-%d" 2>/dev/null || echo "2025-01-01")

cat >> "$REPORT_FILE" <<EOF

---

## 3. Trending Rust Repositories (stars > 500, pushed since $SINCE_DATE)

| Repository | Stars | Description | Created | Topics |
|------------|------:|-------------|---------|--------|
EOF

echo "Fetching trending Rust repos ..." >&2
TRENDING=$(gh_api_raw "search/repositories?q=language:rust+stars:>500+pushed:>$SINCE_DATE&sort=stars&order=desc&per_page=15")

echo "$TRENDING" | jq -r '
  .items[]? |
  "| [\(.full_name)](https://github.com/\(.full_name)) | \(.stargazers_count) | \(.description // "" | gsub("[\\n\\r|]"; " ") | if length > 80 then .[:77] + "..." else . end) | \(.created_at[:10]) | \((.topics // []) | join(", ")) |"
' >> "$REPORT_FILE" 2>/dev/null || echo "| _(API rate limited or no results)_ | | | | |" >> "$REPORT_FILE"

# ---------------------------------------------------------------------------
# Check awesome lists for new/relevant entries
# ---------------------------------------------------------------------------

cat >> "$REPORT_FILE" <<'EOF'

---

## 4. Awesome Lists — Recent Activity

EOF

AWESOME_REPOS=(
  "awesome-selfhosted/awesome-selfhosted"
  "rust-unofficial/awesome-rust"
  "agarrharr/awesome-cli-apps"
)

for repo in "${AWESOME_REPOS[@]}"; do
  echo "Checking recent commits on $repo ..." >&2
  commits_json=$(gh_api "repos/$repo/commits?per_page=5")

  cat >> "$REPORT_FILE" <<EOF
### [\`$repo\`](https://github.com/$repo)

| Date | Author | Message |
|------|--------|---------|
EOF

  echo "$commits_json" | jq -r '
    .[]? |
    "| \(.commit.author.date[:10]) | \(.commit.author.name // "?") | \(.commit.message | split("\n")[0] | gsub("[|]"; "/") | if length > 100 then .[:97] + "..." else . end) |"
  ' >> "$REPORT_FILE" 2>/dev/null || echo "| _(unavailable)_ | | |" >> "$REPORT_FILE"

  echo "" >> "$REPORT_FILE"
  sleep 1
done

# ---------------------------------------------------------------------------
# arXiv — recent PQC / cryptography papers relevant to Phase 3
# ---------------------------------------------------------------------------

cat >> "$REPORT_FILE" <<'EOF'

---

## 5. arXiv — Recent PQC & Cryptography Papers

*Searches cs.CR (Cryptography and Security) for papers on ML-KEM, lattice-based
crypto, post-quantum, and hybrid KEM published in the last 90 days.*

| Date | Title | Authors | arXiv ID |
|------|-------|---------|----------|
EOF

arxiv_search() {
  local query="$1"
  local label="$2"
  # arXiv API: free, no auth required, returns Atom XML
  local url="https://export.arxiv.org/api/query?search_query=${query}&sortBy=submittedDate&sortOrder=descending&max_results=8"
  local raw
  raw=$(curl -s --max-time 15 "$url" 2>/dev/null) || { echo "  _(arXiv unavailable)_" >> "$REPORT_FILE"; return; }

  # Parse Atom XML with basic text processing (no xmllint dependency)
  # Each <entry> block contains <published>, <title>, <author><name>, <id>
  echo "$raw" | awk '
    BEGIN { RS="</entry>"; FS="\n"; title=""; date=""; authors=""; arxiv_id="" }
    /<entry>/ {
      # Extract date (first 10 chars of <published>)
      match($0, /<published>([^T]+)/, arr); date=arr[1]
      # Extract title (strip tags, trim whitespace)
      match($0, /<title>([^<]+)</, arr); title=arr[1]
      gsub(/^[ \t]+|[ \t]+$/, "", title)
      # Extract first author
      match($0, /<name>([^<]+)</, arr); authors=arr[1]
      # Extract arXiv ID (last part of <id> URL)
      match($0, /<id>http[^/]+\/abs\/([^<]+)</, arr); arxiv_id=arr[1]
      if (title != "" && arxiv_id != "") {
        # Truncate long titles
        if (length(title) > 90) title=substr(title, 1, 87) "..."
        printf "| %s | %s | %s et al. | [%s](https://arxiv.org/abs/%s) |\n", \
          date, title, authors, arxiv_id, arxiv_id
      }
    }
  ' >> "$REPORT_FILE" 2>/dev/null || true
}

echo "Fetching arXiv PQC papers ..." >&2

# ML-KEM / CRYSTALS-Kyber
arxiv_search "cat:cs.CR+AND+%28ml-kem+OR+kyber+OR+%22module+lattice%22%29" "ML-KEM"
sleep 3

# Post-quantum / hybrid KEM
arxiv_search "cat:cs.CR+AND+%28%22post-quantum%22+AND+%22hybrid+kem%22%29" "Hybrid KEM"
sleep 3

# Lattice-based cryptography (broader)
arxiv_search "cat:cs.CR+AND+%22lattice-based+cryptography%22" "Lattice"
sleep 2

# ---------------------------------------------------------------------------
# Actionable takeaways
# ---------------------------------------------------------------------------

cat >> "$REPORT_FILE" <<'EOF'
---

## 6. Actionable Takeaways for copypaste.fyi

Review the data above and consider:

- **Star velocity**: Which competitors are growing fastest? What are they doing right (README quality, demo GIFs, blog posts)?
- **Feature gaps**: Are competitors shipping features we lack (E2E encryption, CLI clients, S3 backends, syntax highlighting)?
- **Rust CLI patterns**: What do the gold-standard Rust projects do for CI, release automation, cross-compilation, and shell completions?
- **Awesome-list presence**: Is copypaste.fyi listed on any awesome list yet? If not, submit PRs once the project is mature.
- **SEO & discoverability**: Check if competitors use GitHub Topics effectively — we should too.
- **PQC papers**: Any new attacks on ML-KEM? Papers on X-Wing / hybrid KEM? Relevant to Phase 3 post-quantum roadmap (issue #41).

---

*This report was auto-generated by [`scripts/auto-research.sh`](../blob/main/scripts/auto-research.sh).*
EOF

# ---------------------------------------------------------------------------
# Ensure the "research" label exists
# ---------------------------------------------------------------------------

echo "Ensuring 'research' label exists ..." >&2
gh label create "research" --description "Auto-research findings" --color "7057FF" 2>/dev/null || true

# ---------------------------------------------------------------------------
# Create GitHub issue
# ---------------------------------------------------------------------------

echo "Creating GitHub issue ..." >&2
ISSUE_URL=$(gh issue create \
  --title "[Auto-Research] Competitive Intelligence Report — $DATE" \
  --label "research" \
  --body-file "$REPORT_FILE")

echo "Issue created: $ISSUE_URL"

rm -f "$REPORT_FILE"
